import { Inter, Bebas_Neue } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";
// import Navbar from "@/components/globals/Navbar";
// import Footer from "@/components/globals/Footer";
import FooterWrapper from "@/components/globals/FooterWrapper";
import { fetchPageSEOData } from "@/sanity/api";

const inter = Inter({ subsets: ["latin"], variable: "--font-body" });
const bebasNeue = Bebas_Neue({subsets: ["latin"], weight: ["400"], variable: "--font-subheading" });

const ppNeueMontreal = localFont({
    src: [
        {
            path: "../../public/fonts/PPNeueMontreal-Light.woff2",
            weight: "300",
            style: "normal",
        },
        {
            path: "../../public/fonts/PPNeueMontreal-Book.woff2",
            weight: "350",
            style: "normal",
        },
        {
            path: "../../public/fonts/PPNeueMontreal-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/PPNeueMontreal-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "../../public/fonts/PPNeueMontreal-Bold.woff2",
            weight: "700",
            style: "normal",
        }
    ],
    variable: "--font-body",
})

const instrumentSerif = localFont({
    src: [
        {
            path: "../../public/fonts/InstrumentSerif-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/InstrumentSerif-Italic.woff2",
            weight: "400",
            style: "italic",
        }
    ],
    variable: "--font-serif",
})

const commitMono = localFont({
    src: [
        {
            path: "../../public/fonts/CommitMono-400-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../../public/fonts/CommitMono-700-Regular.woff2",
            weight: "700",
            style: "normal",
        }
    ],
    variable: "--font-mono",
});

// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export async function generateMetadata({ params }) {
    const seoData = await fetchPageSEOData("/")
  
    return {
      title: seoData?.title,
      description: seoData?.description,
    }
  }

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.variable} ${instrumentSerif.variable} ${ppNeueMontreal.variable} ${bebasNeue.variable} ${commitMono.variable}`}>
                {/* <Navbar /> */}
                {children}
                <FooterWrapper />
                {/* <Footer /> */}
            </body>
        </html>
    );
}
